### ISSUE TITLE
Add screenshot to readme

### ISSUE THREAD

**Issue by Lakitna** [fluffynuts/mocha-yar#2]
I was curious about your reporter, but the lack of screenshot means I have to actually download it and try it out.

It would be much quicker for me if you could provide a basic screenshot of how `mocha-yar` looks.

**Comment by fluffynuts** [comment]
Thanks for the interest! I wrote `mocha-yar` many, many, _many_ moons ago, so I had to blow some cobwebs off to get back into it.

I've updated the package:
- the README.md has example gifs
- tested with the latest `gulp-mocha` which broke compatibility with prior invocations, so I've bumped to major version 2, _just in case I break stuff for someone using older mocha / gulp_
